#--spring.config.location  --spring.profiles.active=test
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: ff728_user
    password: FF728hb#180629
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.88.1.86:3306/ff728?characterEncoding=utf-8
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    database: 0
    pool:
      max-active: 600
      max-wait: 60000
      max-idle: 100
      min-idle: 20
    timeout: 60000
    sentinel:
      master: mymaster
      nodes: 10.88.2.76:26379,10.88.1.89:26379
  rabbitmq:
    addresses: 10.88.1.87:5672,10.88.2.74:5672
    username: ff728pro
    password: ff728pro
    virtual-host: 728_activity_redpacket_vhost
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#    schema:
#      - classpath:createsql/*.sql
#      - classpath:initdatasql/*.sql
my:
  threadPool:
    corePoolSize: 200
    maximumPoolSize: 500
    keepAliveTime: 60000
    queueLength: 1000
    receiveCorePoolSize: 50
    receiveMaximumPoolSize: 100
    receiveKeepAliveTime: 60000
    receiveQueueLength: 1000
    sendCorePoolSize: 50
    sendMaximumPoolSize: 100
    sendKeepAliveTime: 60000
    sendQueueLength: 1000
server:
  port: 8888
lua:
  path: /home/dev/activity-test/lua